### ISSUE TITLE
[BUG]: LinkedIn Data Source Error 

### ISSUE THREAD

**Issue by CMcGuigan10** [RevealBi/Reveal.Sdk#184]
### SDK Version

None

### Client Framework

Other

### Server Platform

None

### Operating System

Mac

### Description

Dashboards using LinkedIn now have the following error: 

![image](https://github.com/RevealBi/Reveal.Sdk/assets/54678308/f32d91ab-cbcc-4fef-8536-b334ca353833)

Internal issue [AB#34207](https://infragistics.visualstudio.com/14a7928c-44bc-4aed-b2ca-9a0ffbb14d7a/_workitems/edit/34207)

**Comment by CMcGuigan10** [comment]
This is every visual that uses campaign group and name to break down the data. Mac only

**Comment by CMcGuigan10** [comment]
any eta on this one to work again on desktop? 

![image](https://github.com/user-attachments/assets/f1e2ba2e-462d-4cec-a1df-ff1edae23d2f)

**Comment by brianlagunas** [comment]
There is not ETA at this time.

**Comment by CMcGuigan10** [comment]
Ok can we get a fix out for this, it was ok that this was working on web temporarily but we need this to work across devices.

**Comment by brianlagunas** [comment]
We are still reviewing this, but compared to our other bugs, this is a lower priority. We'll see if we can schedule this for our Dec sprint after we have completed the review process.

**Comment by brianlagunas** [comment]
I understand your frustration as this impacts you directly. However, in the larger Slingshot ecosystem, our telemetry stats tell us that we have no external customers using LinkedIn on Mac. We had three customers use LinkedIn back in spring of 2022, but that was on the web only which is functioning as expected. Hence, why the priority of this issue is lower than our existing customer reported bugs.

We are still reviewing this issue to find the source of it. Sometimes during our review process, we find it's actually a very simple fix and can get a fix in right then and there. If not, then the fix needs to be scheduled for implementation. I will let you know what we find after the issue has been thoroughly reviewed.

We will get it fixed... eventually 😄

**Comment by brianlagunas** [comment]
This has been fixed.
