### ISSUE TITLE
[BUG]: Pivot Grid large number formatting not being applied

### ISSUE THREAD

**Issue by kathswa1** [RevealBi/Reveal.Sdk#271]
### SDK Version

1.6.4

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

Pivot table is showing absolute values even when we are selecting million/billion.

steps to reproduce :-

- select period in row
- select line items in values 
- convert the chart in to pivot table 
- open the field setting 
- change the large number formatting into million.
- in bar chart it the million values are visible.

- but in view chart the values are not converted. 

similarly. when selecting a million for a pivot table.

the values are not converting to millions 

**Actual result** 
when I am converting the value to million the functions are not working as expected.
in view, data values are not getting converted into millions. 

**Expected result**
As a user when I convert the value into a million it should be visible in the view data and pivot chart also.

**Comment by brianlagunas** [comment]
When you click the "View Data" buttons to display the underlying data, you are viewing the raw data that is rendering in the chart. This is not a formatted version of the chart data. That is by design.

However, for your issue with the Pivot not respecting the format, this is a known issue that we are tracking internally with AB#28093

**Comment by kathswa1** [comment]
please let us know once it's fixed.
Thanks @brianlagunas
