### ISSUE TITLE
[BUG]: Second filter selections gets reset after first filter selection set

### ISSUE THREAD

**Issue by tinoptilogic** [RevealBi/Reveal.Sdk#284]
### SDK Version

1.7.0

### Client Framework

React

### Server Platform

ASP.NET

### Operating System

Mac

### Description

Initial filter state:

<img width="1348" alt="image" src="https://github.com/user-attachments/assets/3ac9236c-71ee-4712-b39e-dc9c74849a74">

Second filter changed:

<img width="1348" alt="image" src="https://github.com/user-attachments/assets/664b52c6-43d5-4ba8-81ae-d6391225fbd4">

First filter changed:

<img width="1332" alt="image" src="https://github.com/user-attachments/assets/f711f971-691f-417e-8746-7b640651647a">

You can see on the image above that the state of second filter got reset

**Comment by nerzhei** [comment]
Hi @tinoptilogic. This is by design. Dashboard filters are chained, so when you select something in the first filter, it also affects the available options for the rest. What’s happening here is that the selected options in the second filter are no longer available, which causes the filter to reset. If you'd like, you can submit a feature request to propose changes to this behavior.
