### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by mahtnar** [RevealBi/Reveal.Sdk#285]
### SDK Version

1.6.4

### Client Framework

Angular

### Server Platform

ASP.NET

### Operating System

Windows

### Description

Description:
**Issue**: In this type of chart, the line graphs need to be plotted withing the bar graph. 
![image](https://github.com/user-attachments/assets/9549d44a-c0e2-4888-82e4-eb2fa9533f83)

**Expectation**: The dots need to be withing the bar

![image](https://github.com/user-attachments/assets/0521cb97-5623-4c27-8848-2f9c14562e4e)

**Comment by brianlagunas** [comment]
This is by design. Your first image is two column series plotted clustered on the same x axis, due to this, the center of the category is in the middle of the two columns, and the line series render their points at the center of the categories. Your second image is a single series, so the line series points render in the center of the column.

You would get the same thing you'd get if you tried to plot this in excel or any other charting library.
