### ISSUE TITLE
[BUG]: Multiplying by numbers less than 1 are wrong

### ISSUE THREAD

**Issue by gauxgaux** [RevealBi/Reveal.Sdk#46]
### Company

Casebook

### SDK Version

1.5.0

### Client Framework

React

### Server Platform

Java

### Steps to recreate

1. Create a visualization with a pivot table or grid
2. Create a pre-calculated field with basic multiplication with a number less than one (ex. [interaction_duration]*.5)
3. Drag your field to Rows and/or Values

### Actual Results
I think it's ignoring the decimal and multiplying by the number without the decimal. (ex. 1 * .5 = 5)

**Comment by Christianig** [comment]
Thank you for this report. After reviewing it, we found that the error occurred due to using ".5" instead of "0.5". The problem was resolved by replacing ".5" with "0.5" in the operation.

You might want to add a feature request for adding the ability to use ".x" as well as "0.x" for operations.
This issue is closed for this reason.
