### ISSUE TITLE
The table names that listed at the database setup process, could be further grouped in custom groups, and listed as a tree

### ISSUE THREAD

**Issue by cleverdog** [RevealBi/Reveal.Sdk#5]
The table names that listed at the database setup process like blow image.

![image](https://user-images.githubusercontent.com/5829221/220261358-8bcecbaf-4cf2-4554-9105-82975a8755b3.png)

I want it to be further grouped in custom groups, and listed as a tree.

for example:
a)    Custom_Group1
     	--     i.    Table1
        --	 ii.    Table2
b)    Custom_Group2
         -- 	i.    Table3
        -- 	ii.    Table4

Thank you.

**Comment by brianlagunas** [comment]
How would your API look to enable this behavior? How would you determine what table is in a specific group? Would this happen on the client or server? Does this apply to other tabs such as views, and stored procedures. Does this apply to specific data sources are all data sources?

**Comment by colinzhy** [comment]
Is that possible to expose an interface that allow us to orginze the table/column data in Java SDK, Instead of querying from database meta data directly? Then we can do whatever we want as your interface definitioin.

For your information, we have another table to record the table and column meta data, in our system, we will only expose part of these tables/column to user interface according to user request.

**Comment by colinzhy** [comment]
Is that possible to expose an interface that allow us to orginze the table/column data in Java SDK, Instead of querying from database meta data directly? Then we can do whatever we want as your interface definitioin.

For your information, we have another table to record the table and column meta data, in our system, we will only expose part of these tables/column to user interface according to user request.

**Comment by brianlagunas** [comment]
Unfortunately, it's not as simple as adding an interface.  This would be a major effort and require redesigning some major parts of the SDK. We also have to consider security in terms of being able to provide this information from the server, but at the same time be able to use fake table names, or more descriptive table names, that actually map to the correct table names in the data source when we go to fetch the data.

We will not be considering this request for implemented any time soon. However, I will keep this request open for further feedback from the community.

**Comment by colinzhy** [comment]
Sorry for later response, what I mean is not a interface like Restful API, but I want an programing Interface which you can have a default implementation and we can override it with some coding. For example, there is a class PostgresMetadataProvider with method getTablesAndViews in Java SDK, reveal get the Database metadata by this method, and what I want is to take the minimal effort and get the metadata by ourselves and orginaze it as your pre-defined structure.

**Comment by brianlagunas** [comment]
I am closing this as it has been identified as something that we will not be implementing. Thank you for taking the time to submit this request.
